[package]
name = "arcdps-bhud"
version = "0.2.3"
authors = ["Greaka <mrgreaka@gmail.com>"]
edition = "2018"

[dependencies.arcdps_bindings]
version = "0.1.3"
git = "https://github.com/greaka/arcdps_bindings"
# path="../arcdps_bindings"

[dependencies.winapi]
version = "0.3.7"
features = ["ntdef", "minwindef"]

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
