[package]
name = "arcdps-bhud"
version = "0.1.0"
authors = ["Greaka <mrgreaka@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
arcdps_bindings = { git = "https://github.com/greaka/arcdps_bindings" }
named_pipe = "0.4"
stopwatch = "0.0"
bytes = "0.4"
prost = "0.5"
proclist = "0.9"

[dependencies.winapi]
version = "0.3"
features = ["ntdef", "minwindef"]

[build-dependencies]
prost-build = "0.5"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
