name: Earthly

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build
        if: ${{ github.event_name == 'push' && github.ref_name == github.event.repository.default_branch }}
        run: earthly --ci --push -a '+addon/*' ./
      - name: Run build
        if: ${{ !(github.event_name == 'push' && github.ref_name == github.event.repository.default_branch) }}
        run: earthly --ci -a '+addon/*' ./
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addon
          path: |
            ./*.dll
            ./*.pdb
